version: "3.9"

services:
  web:
    build:
      context: ..
      dockerfile: infrastructure/docker/Dockerfile.web
    volumes:
      - ../public:/usr/share/nginx/html:ro
    ports:
      - "8080:80"
    depends_on:
      - api
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 5s
      retries: 3

  api:
    build:
      context: ..
      dockerfile: infrastructure/docker/Dockerfile.api
    environment:
      - PORT=3000
      - DATABASE_URL=postgres://catalogo:catalogo@db:5432/catalogo
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 5s
      retries: 3

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=catalogo
      - POSTGRES_USER=catalogo
      - POSTGRES_PASSWORD=seguro
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./seeds/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalogo"]
      interval: 10s
      timeout: 5s
      retries: 5

  admin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@example.com
      - PGADMIN_DEFAULT_PASSWORD=catalogo
    ports:
      - "5050:80"
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/login"]
      interval: 60s
      timeout: 10s
      retries: 3

volumes:
  db-data:
